In [1]:
from pathlib import Path
import pandas as pd

PROJECT_DIR = Path(r"D:\AI-MSU")
RAW_DIR = PROJECT_DIR / "data" / "raw"
PROCESSED_DIR = PROJECT_DIR / "data" / "processed"
PROCESSED_DIR.mkdir(parents=True, exist_ok=True)

def find_file(filename):
    files = list(RAW_DIR.rglob(filename))
    if len(files) == 0:
        raise FileNotFoundError(filename + " not found")
    return files[0]

logon_path = find_file("logon.csv")
sample = pd.read_csv(logon_path, nrows=10000)
print("Rows and columns before cleaning:", sample.shape)
display(sample.head())

Rows and columns before cleaning: (10000, 5)

                         id                 date     user       pc activity
0  {X1D9-S0ES98JV-5357PWMI}  01/02/2010 06:49:00  NGF0157  PC-6056    Logon
1  {G2B3-L6EJ61GT-2222RKSO}  01/02/2010 06:50:00  LRR0148  PC-4275    Logon
2  {U6Q3-U0WE70UA-3770UREL}  01/02/2010 06:53:04  LRR0148  PC-4124    Logon
3  {I0N5-R7NA26TG-6263KNGM}  01/02/2010 07:00:00  IRM0931  PC-7188    Logon
4  {D1S0-N6FH62BT-5398KANK}  01/02/2010 07:00:00  MOH0273  PC-6699    Logon

In [2]:
print("Missing values in each column:")
display(sample.isnull().sum().sort_values(ascending=False))

print("Duplicate rows:", sample.duplicated().sum())

Missing values in each column:

id          0
date        0
user        0
pc          0
activity    0
dtype: int64

Duplicate rows: 0

In [3]:
cleaned = sample.drop_duplicates().copy()

if "date" in cleaned.columns:
    cleaned["date"] = pd.to_datetime(cleaned["date"], errors="coerce")

if "user" in cleaned.columns:
    cleaned = cleaned.dropna(subset=["user"])

print("Rows and columns after cleaning:", cleaned.shape)
print("Missing values after cleaning:")
display(cleaned.isnull().sum())
display(cleaned.head())

Rows and columns after cleaning: (10000, 5)
Missing values after cleaning:

id          0
date        0
user        0
pc          0
activity    0
dtype: int64

                         id                date     user       pc activity
0  {X1D9-S0ES98JV-5357PWMI} 2010-01-02 06:49:00  NGF0157  PC-6056    Logon
1  {G2B3-L6EJ61GT-2222RKSO} 2010-01-02 06:50:00  LRR0148  PC-4275    Logon
2  {U6Q3-U0WE70UA-3770UREL} 2010-01-02 06:53:04  LRR0148  PC-4124    Logon
3  {I0N5-R7NA26TG-6263KNGM} 2010-01-02 07:00:00  IRM0931  PC-7188    Logon
4  {D1S0-N6FH62BT-5398KANK} 2010-01-02 07:00:00  MOH0273  PC-6699    Logon

In [4]:
cleaned.to_csv(PROCESSED_DIR / "logon_cleaning_sample.csv", index=False)
print("Saved a cleaned sample. The full raw file has not been changed.")

Saved a cleaned sample. The full raw file has not been changed.